language: python
dist: xenial
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r testing-requirements.txt"
# command to run tests
script:
  - tests/run_tests.sh

jobs:
  include:
  - stage: format-check
    python:
    - "3.6"
    install:
    - pip install black
    script:
    - black --check --diff -S src

# Deploy to pypi on tagged commit
deploy:
- provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  distributions: sdist
  on:
    tags: true
